# Generated by Django 3.1.5 on 2021-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='users/'),
        ),
    ]
