# Generated by Django 3.1.5 on 2021-01-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='media',
            new_name='picture',
        ),
    ]
